version: '3'

volumes:
  mediadata:
    driver: local

  db:
    driver: local

  uwsgisocket:
    driver: local

services:
  django:
    environment:
      - PYTHONUNBUFFERED=true
    image: blog-django
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Docker/django/Dockerfile
    volumes:
      - ./Djangoproject:/code/
      - ./Docker/django/uwsgi.conf:/uwsgi.conf
      - ./Docker/django/entrypoint.sh:/entrypoint.sh
      - "mediadata:/mediadata"
      - "uwsgisocket:/uwsgisocket"
      - ./backup/media:/backupmedia/
      - ./cmd/django/:/cmd/
    stop_signal: SIGINT
    env_file: .env
    entrypoint: ['/entrypoint.sh']

  nginx:
    image: blog-nginx
    depends_on: ["django"]
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    volumes:
      - ./Djangoproject:/code/
      - ./Docker/nginx/nginx.conf:/tmp/nginx.conf
      - ./Docker/nginx/nginx_uwsgi.conf:/tmp/nginx_uwsgi.conf
      - ./Docker/nginx/nginx_mime.types:/nginx_mime.types
      - ./Docker/nginx/nginx_uwsgi_params:/nginx_uwsgi_params
      - ./Docker/nginx/entrypoint.sh:/entrypoint.sh
      - "mediadata:/mediadata"
      - "uwsgisocket:/uwsgisocket"
      - ./cmd/nginx/:/cmd/
    ports:
      - "80:80"
    command: ['nginx']
    entrypoint: ['/entrypoint.sh']
    env_file: .env

  postgres:
    image: blog-postgres
    build:
      context: .
      dockerfile: Docker/postgres/Dockerfile
    volumes:
      - "db:/db"
      - ./backup/db:/backupdb/
      - ./Docker/postgres/entrypoint.sh:/entrypoint.sh
      - ./Docker/postgres/postgresql.conf:/postgresql.conf
      - ./Docker/postgres/pg_hba.conf:/pg_hba.conf
      - ./cmd/postgres/:/cmd/
    ports:
      - "5432:5432"
    env_file: .env
    entrypoint: ['/entrypoint.sh']
