version: '3'

services:
  web:
    environment:
      - PYTHONUNBUFFERED=true
    image: djangoblog
    build:
      context: .
      dockerfile: Docker/blog/Dockerfile
    volumes:
      - ./Djangoproject:/code
    ports:
      - "80:8000"
    stop_signal: SIGINT
