# Generated by Django 2.0.1 on 2018-01-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180115_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, help_text='The image picture of lab member', upload_to='deployment/media'),
        ),
    ]
