# Generated by Django 2.0.1 on 2018-01-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, help_text='The image picture of lab member', upload_to='static/picture'),
        ),
    ]
